### ISSUE TITLE
void-function acons

### ISSUE THREAD

**Issue by ghost** [mbork/beeminder.el#4]
Hi,

while moving to a new host -- with apparently exactly the same configuration -- I noticed that beeminder-kill-goal resulted in:

  Debugger entered--Lisp error: (void-function acons)

Some more investigation revealed that:
on the old system: -> acons is an alias for ‘cl-acons’ in ‘cl.el’.
on the new system, there is no acons, but: -> cl-acons is a compiled Lisp function in ‘cl-lib.el’.

I suppose my elpa dir is a bit of a mess, and inconsistent between hosts; but the fact is that the old system has older copies of many libraries, probably masking a problem with newer versions. Anyway, I didn't delve too deeply, but simply replaced the sole occurrence of 'acons' in beeminder.el with 'cl-acons' and the issue seems to be resolved.

Thought I'd let you know. And thanks for the great package.

-- p

**Comment by mbork** [comment]
Hi,

and sorry for the delay. I decided to finally look into all issues here. Seems you're right, I fixed that more or less as you suggested. Thanks for the report and the kind words!
